name: Build & Deploy to Cloud Run

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Configure Docker to use Artifact Registry
        run: |
          gcloud auth configure-docker us-west1-docker.pkg.dev

      - name: Build and Push Docker image
        run: |
          IMAGE_URI=us-west1-docker.pkg.dev/my-project/my-repo/my-image:$GITHUB_SHA
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: my-image
          image: us-west1-docker.pkg.dev/my-project/my-repo/my-image:${{ github.sha }}
          region: us-west1





