name: CICD

on:
  push:
    branches: 
     - master
     - develop
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # ✅ 1. Checkout del código
      - name: Checkout repo
        uses: actions/checkout@v4



      # ✅ 4. Autenticarse en GCP
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

      # ✅ 5. Login a Artifact Registry (Docker)
      - name: Login to Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: us-central1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_CREDENTIALS_JSON }}

      # ✅ 6. Build y Push Docker a GCP
      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ vars.ARTIFACT_REPO }}/${{ vars.IMAGE_NAME }}:latest


      # ✅ 7. Deploy a Cloud Run
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: YOUR_CLOUD_RUN_SERVICE_NAME
          image: us-central1-docker.pkg.dev/YOUR_PROJECT/YOUR_REPO/YOUR_IMAGE:latest
          region: us-central1
          allow-unauthenticated: true
