name: CICD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      # ... (pasos para checkout, Node.js setup, install, build) ...

      - name: build-push-docker-gcp-artifact-registry-action

        uses: japerry911/build-push-docker-gcp-artifact-registry-action@v2.4