name: CICD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      # ... (pasos para checkout, Node.js setup, install, build) ...

      - name: Build and Push Docker Image
        uses: ./.github/actions/build-push-gcp # Asumiendo que guardaste la acción en esta ruta
        with:
          gcp_credentials_json: ${{ secrets.GCP_CREDENTIALS }}
          dockerfile_path: ./Dockerfile
          docker_target: production
          tags: my-registry/my-image:latest-${{ github.sha }}
          # build_args: ...

      - name: Deploy to server
        # ... (pasos de despliegue SSH) ...