name: CICD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-push: # Or your job name
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Push Docker Image to Artifact Registry
        uses: japerry911/build-push-docker-gcp-artifact-registry-action@v2.4
        with:
          gcp_credentials_json: ${{ secrets.GCP_CREDENTIALS }} # IMPORTANT: Use a GitHub secret
          dockerfile_path: Dockerfile
      #   docker_target: your_docker_target # Replace with your actual target
          tags: us-central1-docker.pkg.dev/my-repo-githubaction/my_repo/my_app:latest

          enable_cache: true
          # Add other necessary inputs for the japerry911 action

      # ... other steps ...