name: Build and Push Docker Image
 
on:
  push:
    branches:
      - master
      - develop
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
 
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
 
      - name: Configure Docker to use Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
 
      - name: Build and Push
        run: |
          docker build -t us-central1-docker.pkg.dev/pipeline-github-action/my-repo/my_app:latest .
          docker push us-central1-docker.pkg.dev/pipeline-github-action/my-repo/my_app:latest
      
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: my-app-service
          image: us-central1-docker.pkg.dev/pipeline-github-action/my-repo/my_app:latest
          region: us-central1
 
# test