name: Build and Push Docker Image

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1

      - name: Verificar cuenta autenticada
        run: gcloud auth list

      - name: Crear repositorio Artifact Registry (si no existe)
        run: |
          gcloud artifacts repositories describe my-repo --location=us-central1 || \
          gcloud artifacts repositories create my-repo \
            --repository-format=docker \
            --location=us-central1 \
            --description="Repositorio Docker para GitHub Actions"

      - name: Configurar Docker con Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Build and Push Docker Image
        run: |
          docker build -t us-central1-docker.pkg.dev/pipeline-github-action/my-repo/my_app:latest .
          docker push us-central1-docker.pkg.dev/pipeline-github-action/my-repo/my_app:latest

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: my-app-service
          image: us-central1-docker.pkg.dev/pipeline-github-action/my-repo/my_app:latest
          region: us-central1

      - name: Esperar que el servicio Cloud Run esté disponible
        run: |
          echo "Esperando 20 segundos para asegurar que Cloud Run esté listo..."
          sleep 20

      - name: Hacer pública la app (roles/run.invoker)
        run: |
          gcloud run services add-iam-policy-binding my-app-service \
            --member="allUsers" \
            --role="roles/run.invoker" \
            --region=us-central1 \
            --project=pipeline-github-action

      - name: Mostrar URL del servicio
        run: |
          gcloud run services describe my-app-service \
            --region=us-central1 \
            --format="value(status.url)"

# prueba 2

