name: GCP Cloud Run Deployment

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build and Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Authenticate Docker with GCP
      run: gcloud auth configure-docker

    - name: Build Docker Image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/cron-ticker:latest .

    - name: Push Docker Image to GCP Container Registry
      run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/cron-ticker:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy cron-ticker \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/cron-ticker:latest \
          --platform managed \
          --region ${{ secrets.GCP_REGION }} \
          --allow-unauthenticated